Repository TeamGaebaljjang/PoRe_PhotoRecipe, pull requests merged in 2022-12, with the labels that each got.

#37 Feat/피드 팔로잉피드
  src/components/card/Post.jsx
  src/components/card/PostContent.jsx
  src/components/card/PostIcon.jsx
  src/components/card/PostUserInfo.jsx
  src/components/card/PostWrapper.jsx
  src/components/card/postStyle.jsx
  src/pages/Feed/Feed.jsx
Labels: enhancement

#41 Feat/회원가입
  src/components/button/BtnForm.jsx
  src/components/header/HeaderB.jsx
  src/pages/Login/SetProfile/SetProfile.jsx
  src/pages/Login/SetProfile/SetProfileForm.jsx
  src/pages/Login/SetProfile/setProfileStyle.jsx
  src/pages/Login/SignUp/SignUpForm.jsx
  src/pages/Login/formStyle.jsx
  src/routes/Routes.jsx
  src/styles/globalStyles.jsx
Labels: enhancement

#44 Feat/프로필 포토존 데이터, 팔로잉 팔로워 데이터
  src/components/header/HeaderAllIn.jsx
  src/components/header/HeaderChat.jsx
  src/components/header/HeaderFollower.jsx
  src/components/header/HeaderFollowing.jsx
  src/components/profile/PhotoZoneList.jsx
  src/components/profile/ProfileInfo.jsx
  src/components/user/User.jsx
  src/pages/Profile/Follow/Follower.jsx
  src/pages/Profile/Follow/Following.jsx
  src/pages/Profile/Follow/followStyle.jsx
  src/pages/Profile/Profile.jsx
  src/routes/Routes.jsx
  src/store/followSlice.jsx
  src/store/index.jsx
  src/store/photoZoneSlice.jsx
  src/store/userInfoSlice.jsx
Labels: enhancement

#46 Feat/피드 좋아요 기능 구현(완료)
  src/components/card/Post.jsx
  src/components/card/PostIcon.jsx
  src/components/card/postStyle.jsx
  src/pages/Feed/Feed.jsx
Labels: enhancement

#47 Feat/프로필포토존리스트
  src/components/card/PhotoZone.jsx
  src/components/card/photoZoneStyle.jsx
  src/components/modal/PhotoZoneModal/PhotoZoneModal.jsx
  src/components/modal/PhotoZoneModal/photoZoneModalStyle.jsx
  src/components/navBar/navBarStyle.jsx
  src/components/profile/PhotoZoneList.jsx
  src/components/profile/feedbarStyle.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/profileStyle.jsx
Labels: enhancement

#51 Feat/게시글 작성
  src/components/card/PostWrapper.jsx
  src/components/header/HeaderAllIn.jsx
  src/components/header/HeaderProfile.jsx
  src/components/header/headerStyle.jsx
  src/pages/Profile/UploadPhotoZone/UploadPhotoZone.jsx
  src/pages/Profile/UploadPost/UploadPost.jsx
  src/routes/Routes.jsx
Labels: enhancement

#52 Feat/홈 캐러셀
  src/assets/icons/icon-left-btn.svg
  src/assets/icons/icon-right-btn.svg
  src/components/card/postStyle.jsx
  src/components/header/HeaderB.jsx
  src/components/header/HeaderBSU.jsx
  src/components/navBar/NavBar.jsx
  src/pages/Home/HomeCarousel.jsx
  src/pages/Home/HomeThumbnail.jsx
  src/pages/Home/homeStyle.jsx
  src/pages/PostDetail/PhotoZoneCard/PhotoZoneCard.jsx
  src/routes/Routes.jsx
Labels: enhancement

#54 ✨ Feat : 피드 상세페이지 API 연동 및 페이지 이동
  src/components/card/Post.jsx
  src/components/card/PostContent.jsx
  src/components/card/PostIcon.jsx
  src/pages/Feed/Feed.jsx
  src/pages/PostDetail/PostCard/PostCard.jsx
  src/routes/Routes.jsx
Labels: enhancement

#55 Feat/홈 피드
  src/components/card/postStyle.jsx
  src/components/header/HeaderB.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeFeed.jsx
  src/pages/Home/homeStyle.jsx
  src/pages/PostDetail/PhotoZoneCard/PhotoZoneCard.jsx
Labels: enhancement

#58 Feat/프로필하단모달
  src/components/header/HeaderProfile.jsx
  src/components/modal/UnderModal/ProfileUnderModal.jsx
  src/components/modal/UnderModal/underModalStyle.jsx
  src/pages/Profile/Profile.jsx
Labels: enhancement

#60 Feat/로그아웃
  src/components/modal/ConfirmModal/LogoutModal.jsx
  src/components/modal/ConfirmModal/confirmModalStyle.jsx
  src/components/modal/UnderModal/ProfileUnderModal.jsx
Labels: enhancement

#62 Feat/로그인 인증 라우팅
  src/routes/LoginControl.jsx
  src/routes/Routes.jsx
Labels: enhancement

#64 Feat/피드 댓글 리스트 불러오기 / 댓글 작성 기능(구현중)
  src/components/comment/Comment.jsx
  src/components/comment/CommentForm.jsx
  src/components/comment/CommentWrapper.jsx
  src/components/comment/commentStyle.jsx
  src/pages/Feed/Feed.jsx
  src/pages/PostDetail/PostCard/PostCard.jsx
  src/pages/PostDetail/PostCard/postCardStyle.jsx
Labels: enhancement

#68 Feat/포토존수정
  src/components/card/PhotoZone.jsx
  src/components/card/photoZoneStyle.jsx
  src/components/modal/UnderModal/PZDeleteEditUnder.jsx
  src/components/modal/UnderModal/underModal1.jsx
  src/pages/PostDetail/EditPhotoZoneCard/EditPhotoZoneCard.jsx
  src/routes/Routes.jsx
Labels: enhancement

#69 Feat : 로그인버튼 활성/비활성 구현
  src/pages/Login/LoginForm.jsx
  src/routes/Routes.jsx
Labels: enhancement

#71 Refactor/피드슬라이스
  src/components/card/PostWrapper.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/YourProfile.jsx
  src/store/feedSlice.jsx
  src/store/index.jsx
Labels: refactor

#75 ✨ Feat : 피드 댓글 작성 기능 구현
  src/components/comment/CommentForm.jsx
  src/components/comment/CommentWrapper.jsx
Labels: enhancement

#76 Refactor/피드사진여러개업로드
  src/components/card/Post.jsx
  src/components/card/postStyle.jsx
  src/pages/Profile/UploadPost/UploadPost.jsx
  src/pages/Profile/UploadPost/uploadPostStyle.jsx
Labels: refactor

#77 Feat/edit profile
  .gitignore
  package-lock.json
  package.json
  src/components/comment/CommentWrapper.jsx
  src/components/header/HeaderBSM.jsx
  src/components/modal/UnderModal/ProfileUnderModal.jsx
  src/pages/Map/KakaoMap.jsx
  src/pages/Map/Map.jsx
  src/pages/Map/MapModal.jsx
  src/pages/Map/ModalWrapper.jsx
  src/pages/Map/mapStyle.jsx
  src/pages/Profile/EditProfile/EditProfileForm.jsx
  src/pages/Profile/EditProfile/FormStyle.jsx
  src/pages/Profile/EditProfile/editProfileStyle.jsx
  src/pages/Profile/UploadPost/UploadPost.jsx
  src/routes/Routes.jsx
Labels: enhancement

#80 Feat/팔로잉 리스트 없을 때 피드 화면 추가
  src/components/card/Post.jsx
  src/components/card/PostIcon.jsx
  src/components/comment/Comment.jsx
  src/components/comment/CommentForm.jsx
  src/pages/Feed/Feed.jsx
  src/pages/PostDetail/PostCard/PostCard.jsx
Labels: enhancement

#86 :bug: Fix : key값 지정
  src/components/card/Post.jsx
  src/components/modal/PhotoZoneModal/PhotoZoneModal.jsx
  src/components/profile/PhotoZoneList.jsx
  src/pages/Home/HomeCarousel.jsx
  src/pages/Home/HomeFeed.jsx
  src/pages/Home/HomeSpotBtn.jsx
  src/pages/Home/HomeThumbnail.jsx
  src/pages/Profile/Follow/Follower.jsx
  src/pages/Profile/Follow/Following.jsx
  src/pages/Profile/UploadPost/UploadPost.jsx
  src/pages/Search/Search.jsx
Labels: bug

#88 ✨ Feat : 피드 댓글 삭제 기능 추가
  src/components/comment/Comment.jsx
  src/components/comment/CommentForm.jsx
  src/components/comment/CommentWrapper.jsx
  src/components/modal/UnderModal/CommentDeleteModal.jsx
  src/components/modal/UnderModal/underModalStyle.jsx
  src/pages/PostDetail/PostCard/PostCard.jsx
  src/pages/Profile/profileStyle.jsx
Labels: enhancement

#92 Feat/채팅방연결
  src/components/header/HeaderChat.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/routes/Routes.jsx
Labels: enhancement

#94 :sparkles: Feat : 피드 프로필 연결 완료
  src/components/card/PostUserInfo.jsx
Labels: enhancement

#96 ✨ Feat : 홈 포토존 상세페이지의 유저 클릭시 해당 프로필 이동
  src/pages/Home/HomeFeed.jsx
  src/pages/PostDetail/PhotoZoneCard/PhotoZoneCard.jsx
Labels: enhancement

#97 Feat/피드 댓글작성란 기능 추가
  src/components/comment/CommentForm.jsx
  src/components/comment/CommentWrapper.jsx
  src/pages/PostDetail/PostCard/postCardStyle.jsx
  src/pages/Profile/Profile.jsx
Labels: enhancement

#99 ✨ Feat : 타 유저 프로필 팔로우 토글 버튼
  src/components/profile/ProfileInfo.jsx
  src/components/profile/profileInfoStyle.jsx
  src/pages/Profile/YourProfile.jsx
Labels: enhancement

#100 Feat/피드수정
  src/components/card/Post.jsx
  src/components/card/PostUserInfo.jsx
  src/components/card/postStyle.jsx
  src/components/modal/ConfirmModal/FeedDeleteModal.jsx
  src/components/modal/UnderModal/FeedEditUnder.jsx
  src/pages/PostDetail/EditPostCard/EditPostCard.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/UploadPost/UploadPost.jsx
  src/pages/Profile/UploadPost/uploadPostStyle.jsx
  src/routes/Routes.jsx
Labels: enhancement

#105 ✨ Feat : 피드 게시글 신고 기능 추가
  src/components/card/PostUserInfo.jsx
  src/components/modal/ConfirmModal/LogoutModal.jsx
  src/components/modal/ConfirmModal/ReportMiniModal.jsx
  src/components/modal/UnderModal/CommentDeleteModal.jsx
  src/components/modal/UnderModal/FeedEditUnder.jsx
  src/pages/Login/LoginForm.jsx
  src/pages/Profile/Profile.jsx
Labels: enhancement

#108 Feat/피드등록시사진삭제
  src/pages/PostDetail/EditPostCard/EditPostCard.jsx
  src/pages/Profile/UploadPost/UploadPost.jsx
  src/pages/Profile/UploadPost/uploadPostStyle.jsx
Labels: enhancement

#109 Feat/포토존등록시사진취소
  src/pages/PostDetail/EditPhotoZoneCard/EditPhotoZoneCard.jsx
  src/pages/Profile/UploadPhotoZone/UploadPhotoZone.jsx
  src/pages/Profile/UploadPhotoZone/uploadPhotoZoneStyle.jsx
Labels: enhancement, refactor

#111 :sparkles: Feat : 피드 화면 무한 스크롤
  src/pages/Feed/Feed.jsx
Labels: enhancement

#117 ✨ Feat : 검색 키워드에 따른 포토존 모달 표시
  public/index.html
  src/assets/icons/icon-marker.svg
  src/components/header/HeaderBSM.jsx
  src/pages/Map/KakaoMap.jsx
  src/pages/Map/Map.jsx
  src/pages/Map/MapModal.jsx
  src/pages/Map/ModalWrapper.jsx
Labels: enhancement

#120 Feat/페이지top버튼
  src/assets/icons/icon-top-default.svg
  src/assets/icons/icon-top-hover.svg
  src/components/button/BtnTop.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Feed/Feed.jsx
  src/pages/Home/Home.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/YourProfile.jsx
Labels: enhancement

#131 📝 Docs : README 폴더트리 작성
  README.md
Labels: documentation

#137 Design/중간 사이즈 반응형 디자인 적용
  e -i HEAD~3
  src/components/button/BtnTop.jsx
  src/components/button/BtnUpload.jsx
  src/components/card/PhotoZone.jsx
  src/components/card/photoZoneStyle.jsx
  src/components/card/postStyle.jsx
  src/components/header/HeaderBSM.jsx
  src/components/header/HeaderFeed.jsx
  src/components/header/headerStyle.jsx
  src/components/modal/ConfirmModal/confirmModalStyle.jsx
  src/components/modal/PhotoZoneModal/photoZoneModalStyle.jsx
  src/components/modal/UnderModal/CommentReportModal.jsx
  src/components/modal/UnderModal/FeedEditUnder.jsx
  src/components/modal/UnderModal/PZDeleteEditUnder.jsx
  src/components/modal/UnderModal/underModalStyle.jsx
  src/components/navBar/NavBar.jsx
  src/components/navBar/navBarStyle.jsx
  src/components/profile/Feedbar.jsx
  src/components/profile/feedbarStyle.jsx
  src/components/profile/photoZoneListStyle.jsx
  src/components/profile/profileInfoStyle.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Chat/ChatRoom/chatRoomStyle.jsx
  src/pages/Chat/chatStyle.jsx
  src/pages/Feed/Feed.jsx
  src/pages/Home/homeStyle.jsx
  src/pages/Map/KakaoMap.jsx
  src/pages/Map/mapStyle.jsx
  src/pages/PostDetail/PostCard/PostCard.jsx
  src/pages/PostDetail/PostCard/postCardStyle.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/profileStyle.jsx
  src/pages/Search/searchStyle.jsx
  src/styles/globalStyles.jsx
Labels: styling
